# @author Peter Bell
# Licensed under MIT.  See License file in top level directory.

# Module to define all exceptions generated by the the CFSM class.  Broken out for readability.  Included by CFSM class.
class CFSM
  class OnlyStartOnCFSMClass < Exception; end

  # If the user has derived a class from CFSM but then not instantiated any FSMs in that class, then this is probably an
  # error. Raise an error.
  class EmptyCFSMClass < Exception; end

  # When specifying a transition handler, the user can either do this with a block or with a reference to a method.
  # If the user has specified both, then this is an error.
  #
  # @example
  #    class Telephone < CFSM
  #     state :nothing_happening do
  #       # We are specifying two actions here.
  #       on :incoming_call, :transition => :ringing, :exec => :open_voip do |event|
  #         open_voip_connection
  #       end
  #     end
  class BlockAndExecDefined < Exception; end
  class TooLateToRegisterEvent < Exception; end
  class ComparingDelayedToLiveEvent < Exception; end
  class NonEventBeingCompared < Exception; end
end